# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui03.ui'
#
# Created: Tue Aug  7 15:04:16 2018
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(861, 482)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(50, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.graphicsView = PlotWidget(self.frame_3)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_7.addWidget(self.graphicsView)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.center_freq_label = QtGui.QLabel(self.frame_3)
        self.center_freq_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.center_freq_label.setAutoFillBackground(False)
        self.center_freq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.center_freq_label.setObjectName(_fromUtf8("center_freq_label"))
        self.horizontalLayout_3.addWidget(self.center_freq_label)
        self.fwhm_label = QtGui.QLabel(self.frame_3)
        self.fwhm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fwhm_label.setObjectName(_fromUtf8("fwhm_label"))
        self.horizontalLayout_3.addWidget(self.fwhm_label)
        self.qfactor_label = QtGui.QLabel(self.frame_3)
        self.qfactor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.qfactor_label.setObjectName(_fromUtf8("qfactor_label"))
        self.horizontalLayout_3.addWidget(self.qfactor_label)
        self.intensity_label = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intensity_label.sizePolicy().hasHeightForWidth())
        self.intensity_label.setSizePolicy(sizePolicy)
        self.intensity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.intensity_label.setObjectName(_fromUtf8("intensity_label"))
        self.horizontalLayout_3.addWidget(self.intensity_label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.center_freq = QtGui.QLineEdit(self.frame_3)
        self.center_freq.setObjectName(_fromUtf8("center_freq"))
        self.horizontalLayout_2.addWidget(self.center_freq)
        self.fwhm = QtGui.QLineEdit(self.frame_3)
        self.fwhm.setObjectName(_fromUtf8("fwhm"))
        self.horizontalLayout_2.addWidget(self.fwhm)
        self.qfactor = QtGui.QLineEdit(self.frame_3)
        self.qfactor.setObjectName(_fromUtf8("qfactor"))
        self.horizontalLayout_2.addWidget(self.qfactor)
        self.intensity = QtGui.QLineEdit(self.frame_3)
        self.intensity.setObjectName(_fromUtf8("intensity"))
        self.horizontalLayout_2.addWidget(self.intensity)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scan = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan.sizePolicy().hasHeightForWidth())
        self.scan.setSizePolicy(sizePolicy)
        self.scan.setStyleSheet(_fromUtf8("background-color: rgb(90, 255, 95);\n"
"font: 75 12pt \"Roboto Condensed\";\n"
"color: rgb(0,0,0);\n"
"\n"
""))
        self.scan.setObjectName(_fromUtf8("scan"))
        self.horizontalLayout.addWidget(self.scan)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save.sizePolicy().hasHeightForWidth())
        self.save.setSizePolicy(sizePolicy)
        self.save.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Roboto Condensed\";"))
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout.addWidget(self.save)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.stop = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setStyleSheet(_fromUtf8("background-color: rgb(255, 90, 90);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Roboto Condensed\";\n"
""))
        self.stop.setObjectName(_fromUtf8("stop"))
        self.horizontalLayout.addWidget(self.stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.parameters = QtGui.QWidget()
        self.parameters.setObjectName(_fromUtf8("parameters"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.parameters)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_2 = QtGui.QFrame(self.parameters)
        self.frame_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(200, 200, 200);"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scan_parameter = QtGui.QLabel(self.frame_2)
        self.scan_parameter.setStyleSheet(_fromUtf8("font: 75 12pt \"Roboto Condensed\";"))
        self.scan_parameter.setObjectName(_fromUtf8("scan_parameter"))
        self.verticalLayout_3.addWidget(self.scan_parameter)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.start_freq_label = QtGui.QLabel(self.frame_2)
        self.start_freq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_freq_label.setObjectName(_fromUtf8("start_freq_label"))
        self.horizontalLayout_4.addWidget(self.start_freq_label)
        self.stop_freq_label = QtGui.QLabel(self.frame_2)
        self.stop_freq_label.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_freq_label.setObjectName(_fromUtf8("stop_freq_label"))
        self.horizontalLayout_4.addWidget(self.stop_freq_label)
        self.freq_step_label = QtGui.QLabel(self.frame_2)
        self.freq_step_label.setAlignment(QtCore.Qt.AlignCenter)
        self.freq_step_label.setObjectName(_fromUtf8("freq_step_label"))
        self.horizontalLayout_4.addWidget(self.freq_step_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.start_freq = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_freq.sizePolicy().hasHeightForWidth())
        self.start_freq.setSizePolicy(sizePolicy)
        self.start_freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.start_freq.setObjectName(_fromUtf8("start_freq"))
        self.horizontalLayout_5.addWidget(self.start_freq)
        self.stop_freq = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_freq.sizePolicy().hasHeightForWidth())
        self.stop_freq.setSizePolicy(sizePolicy)
        self.stop_freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.stop_freq.setObjectName(_fromUtf8("stop_freq"))
        self.horizontalLayout_5.addWidget(self.stop_freq)
        self.freq_step = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_step.sizePolicy().hasHeightForWidth())
        self.freq_step.setSizePolicy(sizePolicy)
        self.freq_step.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.freq_step.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.freq_step.setObjectName(_fromUtf8("freq_step"))
        self.horizontalLayout_5.addWidget(self.freq_step)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.iterations_per_point_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iterations_per_point_label.sizePolicy().hasHeightForWidth())
        self.iterations_per_point_label.setSizePolicy(sizePolicy)
        self.iterations_per_point_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.iterations_per_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.iterations_per_point_label.setObjectName(_fromUtf8("iterations_per_point_label"))
        self.horizontalLayout_10.addWidget(self.iterations_per_point_label)
        self.wait_time_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wait_time_label.sizePolicy().hasHeightForWidth())
        self.wait_time_label.setSizePolicy(sizePolicy)
        self.wait_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait_time_label.setObjectName(_fromUtf8("wait_time_label"))
        self.horizontalLayout_10.addWidget(self.wait_time_label)
        self.phase_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_label.sizePolicy().hasHeightForWidth())
        self.phase_label.setSizePolicy(sizePolicy)
        self.phase_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phase_label.setObjectName(_fromUtf8("phase_label"))
        self.horizontalLayout_10.addWidget(self.phase_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.iterations_per_point = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iterations_per_point.sizePolicy().hasHeightForWidth())
        self.iterations_per_point.setSizePolicy(sizePolicy)
        self.iterations_per_point.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.iterations_per_point.setObjectName(_fromUtf8("iterations_per_point"))
        self.horizontalLayout_11.addWidget(self.iterations_per_point)
        self.wait_time = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wait_time.sizePolicy().hasHeightForWidth())
        self.wait_time.setSizePolicy(sizePolicy)
        self.wait_time.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.wait_time.setObjectName(_fromUtf8("wait_time"))
        self.horizontalLayout_11.addWidget(self.wait_time)
        self.phase = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase.sizePolicy().hasHeightForWidth())
        self.phase.setSizePolicy(sizePolicy)
        self.phase.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.phase.setObjectName(_fromUtf8("phase"))
        self.horizontalLayout_11.addWidget(self.phase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.fit_parameter = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_parameter.sizePolicy().hasHeightForWidth())
        self.fit_parameter.setSizePolicy(sizePolicy)
        self.fit_parameter.setStyleSheet(_fromUtf8("font: 75 12pt \"Roboto Condensed\";"))
        self.fit_parameter.setTextFormat(QtCore.Qt.PlainText)
        self.fit_parameter.setObjectName(_fromUtf8("fit_parameter"))
        self.verticalLayout_3.addWidget(self.fit_parameter)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.intensity_fit_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intensity_fit_label.sizePolicy().hasHeightForWidth())
        self.intensity_fit_label.setSizePolicy(sizePolicy)
        self.intensity_fit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.intensity_fit_label.setObjectName(_fromUtf8("intensity_fit_label"))
        self.horizontalLayout_6.addWidget(self.intensity_fit_label)
        self.fwhm_fit_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwhm_fit_label.sizePolicy().hasHeightForWidth())
        self.fwhm_fit_label.setSizePolicy(sizePolicy)
        self.fwhm_fit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fwhm_fit_label.setObjectName(_fromUtf8("fwhm_fit_label"))
        self.horizontalLayout_6.addWidget(self.fwhm_fit_label)
        self.center_frequency_fit_label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center_frequency_fit_label.sizePolicy().hasHeightForWidth())
        self.center_frequency_fit_label.setSizePolicy(sizePolicy)
        self.center_frequency_fit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.center_frequency_fit_label.setObjectName(_fromUtf8("center_frequency_fit_label"))
        self.horizontalLayout_6.addWidget(self.center_frequency_fit_label)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.intensity_fit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intensity_fit.sizePolicy().hasHeightForWidth())
        self.intensity_fit.setSizePolicy(sizePolicy)
        self.intensity_fit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.intensity_fit.setObjectName(_fromUtf8("intensity_fit"))
        self.horizontalLayout_7.addWidget(self.intensity_fit)
        self.fwhm_fit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwhm_fit.sizePolicy().hasHeightForWidth())
        self.fwhm_fit.setSizePolicy(sizePolicy)
        self.fwhm_fit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.fwhm_fit.setObjectName(_fromUtf8("fwhm_fit"))
        self.horizontalLayout_7.addWidget(self.fwhm_fit)
        self.center_frequency_fit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center_frequency_fit.sizePolicy().hasHeightForWidth())
        self.center_frequency_fit.setSizePolicy(sizePolicy)
        self.center_frequency_fit.setBaseSize(QtCore.QSize(40, 20))
        self.center_frequency_fit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.center_frequency_fit.setObjectName(_fromUtf8("center_frequency_fit"))
        self.horizontalLayout_7.addWidget(self.center_frequency_fit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addWidget(self.frame_2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.load_default = QtGui.QPushButton(self.parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_default.sizePolicy().hasHeightForWidth())
        self.load_default.setSizePolicy(sizePolicy)
        self.load_default.setObjectName(_fromUtf8("load_default"))
        self.horizontalLayout_9.addWidget(self.load_default)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.save_default = QtGui.QPushButton(self.parameters)
        self.save_default.setBaseSize(QtCore.QSize(40, 20))
        self.save_default.setObjectName(_fromUtf8("save_default"))
        self.horizontalLayout_9.addWidget(self.save_default)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.parameters, _fromUtf8(""))
        self.conscan = QtGui.QWidget()
        self.conscan.setObjectName(_fromUtf8("conscan"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.conscan)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.graphicsView_2 = PlotWidget(self.conscan)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.verticalLayout_8.addWidget(self.graphicsView_2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.start_con = QtGui.QPushButton(self.conscan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.start_con.sizePolicy().hasHeightForWidth())
        self.start_con.setSizePolicy(sizePolicy)
        self.start_con.setStyleSheet(_fromUtf8("background-color: rgb(90, 255, 95);\n"
"font: 75 12pt \"Roboto Condensed\";\n"
"color: rgb(0,0,0);"))
        self.start_con.setObjectName(_fromUtf8("start_con"))
        self.horizontalLayout_12.addWidget(self.start_con)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.save_continous = QtGui.QPushButton(self.conscan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_continous.sizePolicy().hasHeightForWidth())
        self.save_continous.setSizePolicy(sizePolicy)
        self.save_continous.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Roboto Condensed\";"))
        self.save_continous.setObjectName(_fromUtf8("save_continous"))
        self.horizontalLayout_12.addWidget(self.save_continous)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.stop_con = QtGui.QPushButton(self.conscan)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_con.sizePolicy().hasHeightForWidth())
        self.stop_con.setSizePolicy(sizePolicy)
        self.stop_con.setStyleSheet(_fromUtf8("background-color: rgb(255, 90, 90);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Roboto Condensed\";"))
        self.stop_con.setObjectName(_fromUtf8("stop_con"))
        self.horizontalLayout_12.addWidget(self.stop_con)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.conscan, _fromUtf8(""))
        self.conscanparameters = QtGui.QWidget()
        self.conscanparameters.setObjectName(_fromUtf8("conscanparameters"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.conscanparameters)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.frame_4 = QtGui.QFrame(self.conscanparameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(200, 200, 200);"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.scan_parameter_2 = QtGui.QLabel(self.frame_4)
        self.scan_parameter_2.setStyleSheet(_fromUtf8("font: 75 12pt \"Roboto Condensed\";"))
        self.scan_parameter_2.setObjectName(_fromUtf8("scan_parameter_2"))
        self.verticalLayout_10.addWidget(self.scan_parameter_2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.measurementsperpoint_cont_label = QtGui.QLabel(self.frame_4)
        self.measurementsperpoint_cont_label.setAlignment(QtCore.Qt.AlignCenter)
        self.measurementsperpoint_cont_label.setObjectName(_fromUtf8("measurementsperpoint_cont_label"))
        self.horizontalLayout_13.addWidget(self.measurementsperpoint_cont_label)
        self.x_range_cont_label = QtGui.QLabel(self.frame_4)
        self.x_range_cont_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_range_cont_label.setObjectName(_fromUtf8("x_range_cont_label"))
        self.horizontalLayout_13.addWidget(self.x_range_cont_label)
        self.phase_cont_label = QtGui.QLabel(self.frame_4)
        self.phase_cont_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phase_cont_label.setObjectName(_fromUtf8("phase_cont_label"))
        self.horizontalLayout_13.addWidget(self.phase_cont_label)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.measurementsperpoint_cont = QtGui.QLineEdit(self.frame_4)
        self.measurementsperpoint_cont.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.measurementsperpoint_cont.setObjectName(_fromUtf8("measurementsperpoint_cont"))
        self.horizontalLayout_14.addWidget(self.measurementsperpoint_cont)
        self.x_range_cont = QtGui.QLineEdit(self.frame_4)
        self.x_range_cont.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.x_range_cont.setObjectName(_fromUtf8("x_range_cont"))
        self.horizontalLayout_14.addWidget(self.x_range_cont)
        self.phase_cont = QtGui.QLineEdit(self.frame_4)
        self.phase_cont.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.phase_cont.setObjectName(_fromUtf8("phase_cont"))
        self.horizontalLayout_14.addWidget(self.phase_cont)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.wait_time_cont_label = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wait_time_cont_label.sizePolicy().hasHeightForWidth())
        self.wait_time_cont_label.setSizePolicy(sizePolicy)
        self.wait_time_cont_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait_time_cont_label.setObjectName(_fromUtf8("wait_time_cont_label"))
        self.horizontalLayout_16.addWidget(self.wait_time_cont_label)
        self.lock_in_frequency_cont_label = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lock_in_frequency_cont_label.sizePolicy().hasHeightForWidth())
        self.lock_in_frequency_cont_label.setSizePolicy(sizePolicy)
        self.lock_in_frequency_cont_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lock_in_frequency_cont_label.setObjectName(_fromUtf8("lock_in_frequency_cont_label"))
        self.horizontalLayout_16.addWidget(self.lock_in_frequency_cont_label)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.wait_time_cont = QtGui.QLineEdit(self.frame_4)
        self.wait_time_cont.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.wait_time_cont.setObjectName(_fromUtf8("wait_time_cont"))
        self.horizontalLayout_17.addWidget(self.wait_time_cont)
        self.lock_in_frequency_cont = QtGui.QLineEdit(self.frame_4)
        self.lock_in_frequency_cont.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lock_in_frequency_cont.setObjectName(_fromUtf8("lock_in_frequency_cont"))
        self.horizontalLayout_17.addWidget(self.lock_in_frequency_cont)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addWidget(self.frame_4)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem12)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.load_default_cont = QtGui.QPushButton(self.conscanparameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_default_cont.sizePolicy().hasHeightForWidth())
        self.load_default_cont.setSizePolicy(sizePolicy)
        self.load_default_cont.setObjectName(_fromUtf8("load_default_cont"))
        self.horizontalLayout_15.addWidget(self.load_default_cont)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.save_default_cont = QtGui.QPushButton(self.conscanparameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_default_cont.sizePolicy().hasHeightForWidth())
        self.save_default_cont.setSizePolicy(sizePolicy)
        self.save_default_cont.setObjectName(_fromUtf8("save_default_cont"))
        self.horizontalLayout_15.addWidget(self.save_default_cont)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.conscanparameters, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.close = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setMinimumSize(QtCore.QSize(0, 0))
        self.close.setSizeIncrement(QtCore.QSize(0, 0))
        self.close.setBaseSize(QtCore.QSize(0, 0))
        self.close.setIconSize(QtCore.QSize(30, 24))
        self.close.setObjectName(_fromUtf8("close"))
        self.horizontalLayout_8.addWidget(self.close)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ResoSca", None))
        self.center_freq_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Fit result for the center frequency.</p></body></html>", None))
        self.center_freq_label.setText(_translate("MainWindow", "Center Frequency", None))
        self.fwhm_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Fit result for the <span style=\" text-decoration: underline;\">F</span>ull <span style=\" text-decoration: underline;\">W</span>idth at<span style=\" text-decoration: underline;\"> H</span>alf <span style=\" text-decoration: underline;\">M</span>aximum.</p></body></html>", None))
        self.fwhm_label.setText(_translate("MainWindow", "FWHM", None))
        self.qfactor_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Fit result for the Q - factor.</p><p>Q - factor = center frequency / FWHW</p></body></html>", None))
        self.qfactor_label.setText(_translate("MainWindow", "Q - Factor", None))
        self.intensity_label.setText(_translate("MainWindow", "Intensity", None))
        self.scan.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start the measurement.</p></body></html>", None))
        self.scan.setText(_translate("MainWindow", "Scan", None))
        self.save.setToolTip(_translate("MainWindow", "<html><head/><body><p>save</p></body></html>", None))
        self.save.setText(_translate("MainWindow", "save", None))
        self.stop.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stop the measurement.</p></body></html>", None))
        self.stop.setText(_translate("MainWindow", "Stop Scan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Resonance Scan", None))
        self.scan_parameter.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.scan_parameter.setText(_translate("MainWindow", "Resonance Scan Parameters", None))
        self.start_freq_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Begin of the frequency intervall of the measurement.</p></body></html>", None))
        self.start_freq_label.setText(_translate("MainWindow", "Start Frequency (Hz)", None))
        self.stop_freq_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>End of the frequency intervall of the measurement.</p></body></html>", None))
        self.stop_freq_label.setText(_translate("MainWindow", "Stop Frequency (Hz)", None))
        self.freq_step_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Difference between the measured data-points. Lower values give higher resolution and longer measure time. </p><p>Minimal step-width is 0.026 Hz.</p></body></html>", None))
        self.freq_step_label.setText(_translate("MainWindow", "Frequency Step Width(Hz)", None))
        self.iterations_per_point_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of points to recorad at each frequency, to integrate over.</p></body></html>", None))
        self.iterations_per_point_label.setText(_translate("MainWindow", "Measurements per Point (#)", None))
        self.wait_time_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Wait time between the adjustment of a frequency and the measurement at that frequency. Higher Q-factors require higher wait times, due to higher setteling times. </p></body></html>", None))
        self.wait_time_label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Wait time between the setting of a frequency and the measurement at these frequency. Higher Q-factors require higher wait times.</p></body></html>", None))
        self.wait_time_label.setText(_translate("MainWindow", "Setteling Time (s)", None))
        self.phase_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Phase shift <span style=\" font-family:\'sans-serif\'; font-size:14px; font-weight:600; color:#222222; background-color:#ffffff;\">φ</span> of the lock in reference signal. 11.5Deg &lt; -<span style=\" font-family:\'sans-serif\'; font-size:14px; font-weight:600; color:#222222; background-color:#ffffff;\">φ </span><span style=\" font-family:\'sans-serif\'; font-size:14px; font-weight:400; color:#222222; background-color:#ffffff;\">&lt; |176</span>Deg| (hardware limited). Enter positive values.</p></body></html>", None))
        self.phase_label.setText(_translate("MainWindow", "Phase (Deg)", None))
        self.fit_parameter.setText(_translate("MainWindow", "Initial Fit Parameters", None))
        self.intensity_fit_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guess of the intensity of the signal as initial parameter for the fit.</p></body></html>", None))
        self.intensity_fit_label.setText(_translate("MainWindow", "Intensity (0 - 2000)", None))
        self.fwhm_fit_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guess of the <span style=\" text-decoration: underline;\">F</span>ull <span style=\" text-decoration: underline;\">W</span>idth at <span style=\" text-decoration: underline;\">H</span>alf <span style=\" text-decoration: underline;\">M</span>aximum of the signal as initial parameter for the fit.</p></body></html>", None))
        self.fwhm_fit_label.setText(_translate("MainWindow", "FWHM (Hz)", None))
        self.center_frequency_fit_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guess of the center frequency of the signal as initial parameter for the fit.</p></body></html>", None))
        self.center_frequency_fit_label.setText(_translate("MainWindow", "Center Frequency (Hz)", None))
        self.load_default.setToolTip(_translate("MainWindow", "<html><head/><body><p>Load default parameters.</p></body></html>", None))
        self.load_default.setText(_translate("MainWindow", "Load Default Parameters", None))
        self.save_default.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save all current parameters in a file as default.</p></body></html>", None))
        self.save_default.setText(_translate("MainWindow", "Save as Default Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parameters), _translate("MainWindow", "Resonance Scan Parameters", None))
        self.start_con.setText(_translate("MainWindow", "START", None))
        self.save_continous.setText(_translate("MainWindow", "SAVE", None))
        self.stop_con.setText(_translate("MainWindow", "STOP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.conscan), _translate("MainWindow", "Continuous Scan", None))
        self.scan_parameter_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.scan_parameter_2.setText(_translate("MainWindow", "Continous Scan Parameters", None))
        self.measurementsperpoint_cont_label.setText(_translate("MainWindow", " Measurements per Point [#]", None))
        self.x_range_cont_label.setText(_translate("MainWindow", "X-Range [s]", None))
        self.phase_cont_label.setText(_translate("MainWindow", "Phase [Deg]", None))
        self.wait_time_cont_label.setText(_translate("MainWindow", "Wait Time [s]", None))
        self.lock_in_frequency_cont_label.setText(_translate("MainWindow", "lock in frequency [Hz]", None))
        self.load_default_cont.setText(_translate("MainWindow", "Load Default Parameters", None))
        self.save_default_cont.setText(_translate("MainWindow", "Save as Default Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.conscanparameters), _translate("MainWindow", "Continuous Scan Parameters", None))
        self.close.setToolTip(_translate("MainWindow", "<html><head/><body><p>Get the **** out of here!</p></body></html>", None))
        self.close.setText(_translate("MainWindow", "Close", None))

from pyqtgraph import PlotWidget
